"""
CheeseFactory generates Cheese objects (model instances).
Think of it like Cheese.objects.create(),
but where the cheese data is autogenerated.
instanciate with cheese = CheeseFactory()
that’s no good for looking at, it’s great for testing.
"""

from django.template.defaultfilters import slugify

import factory
import factory.fuzzy

from ..models import Cheese

class CheeseFactory(factory.django.DjangoModelFactory):
    name = factory.fuzzy.FuzzyText()
    slug = factory.LazyAttribute(lambda obj: slugify(obj.name))
    description = factory.Faker(
        'paragraph', nb_sentences=3, variable_nb_sentences=True)
    firmness = factory.fuzzy.FuzzyChoice([x[0] for x in Cheese.Firmness.choices]
                                         )

    class Meta:
        model = Cheese
